#!/bin/bash

secret_name=`kubectl describe serviceAccounts default | grep Tokens: | awk '$1 == "Tokens:" {print $2}'`

token=`kubectl describe secrets ${secret_name} | grep token: | awk '$1 == "token:" {print $2}'`

ca_data=`kubectl config view --flatten --minify | grep client-certificate-data: | awk '$1 == "client-certificate-data:" {print $2}'`

cat <<-_EOT_
apiVersion: v1
kind: Config
users:
- name: default
  user:
    token: ${token}
clusters:
- cluster:
    certificate-authority-data: ${ca_data}
    server: https://localhost:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: default
  name: docker-desktop
current-context: docker-desktop
_EOT_