version: '2'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - '8200:8200'
    restart: always
    volumes:
      - ./vault_config.json:/vault/config/vault.json
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
